name: SYSARCH-ACS Integration Build (push/PR)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run:
    uses: ./.github/workflows/sysarch_ci.yml
    with:
      edk2-ref: edk2-stable202505
      toolchain: arm-toolchain,gcc
      run-uefi: true
      run-baremetal: true
      run-linux: true
    secrets: inherit
